from . import stock_lot
from . import stock_expired_log
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_quant
from . import product_template
from . import product_product
from . import res_config_settings
