from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


class StockPicking(models.Model):
    _inherit = 'stock.picking'

    expired_log_ids = fields.One2many(
        "stock.expired.log",
        "picking_id",
        string="Expired Logs"
    )

    x_transfer_tag = fields.Char(
        string="Transfer Tag",
        help="Set to 'Expired Transfer' for pickings generated by the Expired Medicines module.",
        index=True,
    )
    expired_reason = fields.Text(string="Expired Reason")

    is_expired_transfer = fields.Boolean(compute="_compute_is_expired_transfer")

    @api.depends('move_ids_without_package.location_dest_id')
    def _compute_is_expired_transfer(self):
        for rec in self:
            rec.is_expired_transfer = any(
                m.location_dest_id.is_expired_location
                for m in rec.move_ids_without_package
            )

    def button_validate(self):
        for picking in self:
            if picking.is_expired_transfer and not picking.expired_reason:
                raise UserError(
                    "❌ You must enter a reason when transferring to Expired location."
                )
            # Enforce incoming/outgoing safety checks
            if picking.picking_type_id.code == 'incoming':
                picking._check_incoming_expiry_safety()
            elif picking.picking_type_id.code == 'outgoing':
                picking._check_outgoing_expiry_safety()
                
            picking._check_required_expiry_month_year()
        return super().button_validate()

    def _check_incoming_expiry_safety(self):
        today = fields.Date.context_today(self)
        for picking in self:
            for line in picking.move_line_ids:
                product = line.product_id
                if not product or product.tracking == 'none' or not product.product_tmpl_id.use_expiration_date:
                    continue

                expiry_date = line.expiration_date or (line.lot_id and line.lot_id.expiration_date)
                
                # Check for parsed expiration datetime if present
                if expiry_date and expiry_date.date() < today:
                    raise ValidationError(_(
                        "CRITICAL SAFETY: Cannot receive expired product '%s'. "
                        "Expiry date %s is in the past."
                    ) % (product.display_name, expiry_date.date()))

    def _check_outgoing_expiry_safety(self):
        today = fields.Date.context_today(self)
        for picking in self:
            for line in picking.move_line_ids:
                product = line.product_id
                if not product or product.tracking == 'none' or not product.product_tmpl_id.use_expiration_date:
                    continue

                if line.lot_id and line.lot_id.expiration_date and line.lot_id.expiration_date.date() < today:
                    raise ValidationError(_(
                        "CRITICAL SAFETY: Attempting to deliver an EXPIRED lot!\n"
                        "Product: %s\nLot: %s\nExpired on: %s\n\n"
                        "Please re-assign a valid lot."
                    ) % (product.display_name, line.lot_id.name, line.lot_id.expiration_date.date()))

    def _check_required_expiry_month_year(self):
        for picking in self:
            if picking.picking_type_id.code != 'incoming':
                continue

            for line in picking.move_line_ids:
                product = line.product_id

                if not product:
                    continue

                if product.tracking == 'none':
                    continue

                if not product.product_tmpl_id.use_expiration_date:
                    continue

                expiry_value = line.x_expiry_month_year or line.lot_id.x_expiry_month_year

                if not expiry_value:
                    lot_name = line.lot_name or line.lot_id.name or _('Not set')

                    raise ValidationError(_(
                        'Please enter Expiry Date (MM/YYYY) for product "%s", lot "%s".'
                    ) % (product.display_name, lot_name))