from . import res_config_settings
from . import res_users
from . import product_template
from . import product_pricelist
from . import low_stock_log
from . import sale_commission_entry
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import ir_ui_menu
